# Test workflow on self-hosted runner for node version 16

name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/checkout@v4 # on the runner, check out this code on
      - run: touch test.txt
      - run: echo hello > test.txt
    #   - run: yarn
    #   - run: yarn build
    #   - run: pm2 reload flamingo # reloads on the DigitalOcean droplet
        env:
          CI: true
